#short side
points=[FreeCAD.Vector(39719.0585938,13598.6582031,0.0),FreeCAD.Vector(39726.2617188,13596.6875,0.0),FreeCAD.Vector(39739.640625,13593.7138672,0.0),FreeCAD.Vector(39754.6914062,13592.0419922,0.0),FreeCAD.Vector(39771.0429688,13590.7412109,0.0),FreeCAD.Vector(39785.5351562,13590.7412109,0.0),FreeCAD.Vector(39806.7148438,13591.2988281,0.0),FreeCAD.Vector(39829.7539062,13591.6708984,0.0),FreeCAD.Vector(39851.8671875,13592.4140625,0.0),FreeCAD.Vector(39873.4179688,13592.5996094,0.0),FreeCAD.Vector(39886.0546875,13592.9707031,0.0),FreeCAD.Vector(39902.03125,13595.7578125,0.0),FreeCAD.Vector(39907.7929688,13597.6162109,0.0),FreeCAD.Vector(39911.3242188,13598.7314453,0.0)]

#long side

points=[FreeCAD.Vector(39671.0390625,13517.5419922,0.0),FreeCAD.Vector(39677.9140625,13522.9296875,0.0),FreeCAD.Vector(39689.0625,13529.0615234,0.0),FreeCAD.Vector(39701.5117188,13535.5644531,0.0),FreeCAD.Vector(39717.6757812,13540.953125,0.0),FreeCAD.Vector(39733.8398438,13543.9257812,0.0),FreeCAD.Vector(39746.8476562,13544.6689453,0.0),FreeCAD.Vector(39771.0,13543.9257812,0.0),FreeCAD.Vector(39795.5273438,13544.296875,0.0),FreeCAD.Vector(39812.671875,13543.6523438,0.0),FreeCAD.Vector(39831.9609375,13543.6523438,0.0),FreeCAD.Vector(39852.6132812,13542.7441406,0.0),FreeCAD.Vector(39870.9921875,13543.1982422,0.0),FreeCAD.Vector(39895.5039062,13542.0634766,0.0),FreeCAD.Vector(39913.8867188,13541.3828125,0.0),FreeCAD.Vector(39924.5507812,13540.7021484,0.0),FreeCAD.Vector(39936.125,13537.5253906,0.0),FreeCAD.Vector(39947.4726562,13531.3974609,0.0),FreeCAD.Vector(39955.6445312,13524.5888672,0.0),FreeCAD.Vector(39959.5,13518.2353516,0.0)]

