short_wall_points=[FreeCAD.Vector(0.00470630638301,4.66260480881,0.0),FreeCAD.Vector(0.637861073017,7.10972166061,0.0),FreeCAD.Vector(1.02176041097,10.6289414802,0.0),FreeCAD.Vector(1.02176041097,10.6289414802,0.0),FreeCAD.Vector(0.778971450983,21.8052480313,0.0),FreeCAD.Vector(0.587126255035,22.9024066925,0.0),FreeCAD.Vector(0.350229382515,23.9211769104,0.0),FreeCAD.Vector(-3.80714126891e-09,24.9636802673,0.0),FreeCAD.Vector(-0.0168458539993,23.6835536957,0.0),FreeCAD.Vector(0.265511572361,22.4799594879,0.0),FreeCAD.Vector(0.434572041035,21.5436344147,0.0),FreeCAD.Vector(0.671657562256,10.6298742294,0.0),FreeCAD.Vector(0.483984142542,8.62965393066,0.0),FreeCAD.Vector(0.327295213938,7.2866101265,0.0),FreeCAD.Vector(0.169979244471,6.59615755081,0.0),FreeCAD.Vector(-0.00809708889574,6.39837121964,0.0)]

long_wall_points=[FreeCAD.Vector(8.114361763,-1.73313308149e-09,0.0),FreeCAD.Vector(6.76596832275,2.02290296555,0.0),FreeCAD.Vector(5.7817697525,4.37147188187,0.0),FreeCAD.Vector(5.34317350388,6.25103521347,0.0),FreeCAD.Vector(5.24820184708,7.40167379379,0.0),FreeCAD.Vector(5.19219303131,8.08025836945,0.0),FreeCAD.Vector(5.38900709152,19.0178985596,0.0),FreeCAD.Vector(5.49120235443,24.6972522736,0.0),FreeCAD.Vector(5.50042104721,25.209569931,0.0),FreeCAD.Vector(5.782579422,26.7828884125,0.0),FreeCAD.Vector(6.52353239059,28.184343338,0.0),FreeCAD.Vector(7.6761325305,29.3177150753,0.0),FreeCAD.Vector(8.39999999619,29.3177150753,0.0),FreeCAD.Vector(8.39999999619,29.3177150753,0.0),FreeCAD.Vector(8.39999999619,29.180705981,0.0),FreeCAD.Vector(7.2779006958,28.2872467041,0.0),FreeCAD.Vector(6.98829984665,27.9051761627,0.0),FreeCAD.Vector(6.3922162056,26.9374084473,0.0),FreeCAD.Vector(6.22338151932,26.3484649658,0.0),FreeCAD.Vector(6.00136518478,25.2575359344,0.0),FreeCAD.Vector(5.69533109665,8.03961658478,0.0),FreeCAD.Vector(5.79911661148,6.7148103714,0.0),FreeCAD.Vector(6.11394739151,5.05856561661,0.0),FreeCAD.Vector(6.86278247833,3.03532171249,0.0),FreeCAD.Vector(7.46937465668,1.87837505341,0.0),FreeCAD.Vector(8.39999961853,0.426232159138,0.0),FreeCAD.Vector(8.39999961853,-1.73313308149e-09,0.0)]
